services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    # Zorgt ervoor dat de container 'host.docker.internal' kan resolven naar je lokale machine (XAMPP)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      # Database configuratie voor XAMPP
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=finaletaakcloudcomputing
      - DB_USERNAME=root
      - DB_PASSWORD=
      # gRPC configuratie
      - GRPC_HOST=grpc-server
      - GRPC_PORT=50051
    depends_on:
      - grpc-server
      # - soap-service # Uncomment als je deze service ook gebruikt
    networks:
      - app-network

  # De nieuwe gRPC Java service
  grpc-server:
    build:
      context: ./gRPC_Java
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - app-network

  graphql:
    build:
      context: ./GraphQL
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  mqtt_receiver:
    build:
      context: ./MQTT/MQTT_receiver
    container_name: mqttreceiver
    restart: "on-failure"
    volumes:
      - ./MQTT/MQTT_receiver/plots:/app/plots
    networks:
      - app-network

  mqtt_sender:
    build:
      context: ./MQTT/MQTT_sender
    container_name: mqttsender
    restart: unless-stopped
    depends_on:
      - mqtt_receiver
    command: ["-f", "config/settings.json"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local