services:
  mqtt_receiver_web:
    build:
      context: ./MQTT_receiver_web
    container_name: mqttreceiver
    restart: "on-failure"
    # volumes:
    #   - ./MQTT_receiver/plots:/app/plots

  mqtt_sender:
    build:
      context: ./MQTT_sender
    container_name: mqttsender
    restart: unless-stopped
    depends_on:
      - mqtt_receiver
    command: ["-f", "config/settings.json"]